---
title: "plotly"
author: "Jessie Li"
date: "2023-10-24"
output: 
  html_document:
      toc: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```
Focus on NYC Airbnb data
```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |>
  mutate( star = review_scores_location /2 ) |>
  select(
    borough = neighbourhood_group, 
    neighbourhood, 
    star, 
    price, 
    room_type, 
    lat, 
    long
  ) |>
  drop_na() |>
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```

Let's make a scatterplot!
```{r}
nyc_airbnb |>
  mutate(
    text_label = str_c("Price: $", price, "\nRating:", star)
  ) |>
  plot_ly(
    x = ~lat, y= ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Let's make a boxplot next!
```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(
    y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

Let's make a bar plot!
```{r}
nyc_airbnb |>
  count(neighbourhood) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |>
  plot_ly(
    x = ~neighbourhood, y = ~n, color = ~neighbourhood,
    type = "bar", colors = "viridis"
  )
```

# ggplotly
Prof: don't really use it
```{r}
ggp_scatter =
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(ggp_scatter) #Convert
```





